### ISSUE TITLE
Typo in installation guide

### ISSUE THREAD

**Issue by heathwinning** [breandan/kotlingrad#10]
> ```
> gpr.user=<USERNAME>
> grp.key=<PERSONAL_ACCESS_TOKEN>
> ```
The second line should be `gpr...`.

Confused me for a while with unhelpful "Could not resolve" errors from gradle.

**Comment by breandan** [comment]
Good catch, thanks for pointing this out. We should probably use a different package repo, this whole workflow is a bit complicated just to download a JAR.
