### ISSUE TITLE
Jar file of 0.3.5 not published on jitpack

### ISSUE THREAD

**Issue by bjonnh** [breandan/kotlingrad#16]
See: 

https://jitpack.io/com/github/breandan/kotlingrad/0.3.5/

Compared to:

https://jitpack.io/com/github/breandan/kotlingrad/0.3.4

**Comment by breandan** [comment]
Hi Jon, thank you for reporting this issue! JitPack should now include the JARs properly as of version [`0.3.7`](https://jitpack.io/com/github/breandan/kotlingrad/0.3.7).
