### ISSUE TITLE
Port the library to Kotlin/Multiplatform

### ISSUE THREAD

**Issue by CommanderTvis** [breandan/kotlingrad#24]
**Describe the solution you'd like**
Change the project model to Kotlin/Multiplatform and provide targets other than JVM.

**Comment by breandan** [comment]
Thanks, this is a good suggestion. It should be possible to extract a pure Kotlin subset of this library with no third-party dependencies, put visualization in a separate module and compile to multiplatform. It's been on our todo list for a while.

**Comment by breandan** [comment]
I made some progress on minimizing our JVM dependencies, but think this is going to depend on Kotlin/multik#23 or JetBrains-Research/viktor#50. Some standard library functionality is also lagging behind, such as the [reflection API](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/). Do you have any idea if/when the common standard library will reach parity with its JVM counterpart?

**Comment by CommanderTvis** [comment]
I know there is reflekt project by JetBrains Research that may cover some of JVM relfection uses.
