### ISSUE TITLE
How to add library to project?

### ISSUE THREAD

**Issue by Redrield** [breandan/kotlingrad#3]
Is kotlingrad hosted in any maven repos (such as jcenter or central)? I'd like to use this but I can't find a source to import it from

**Comment by breandan** [comment]
Not yet, but we will make it available on the [GitHub Package Registry](https://github.com/features/package-registry) once our beta access is approved. In the mean time, you can clone and build the source via `git clone https://github.com/breandan/kotlingrad && cd kotlingrad && ./gradlew build`. The JAR file will be placed in `build/libs`. Thanks for your interest!

**Comment by breandan** [comment]
Still waiting for an invite to the GPR Beta. In the meantime, we will serve it on this Git repository directly: https://github.com/breandan/kotlingrad#installation

**Comment by breandan** [comment]
Builds is now distributed on the [GitHub Package Registry](https://github.com/breandan/kotlingrad/packages) (please [see here](https://help.github.com/en/articles/configuring-apache-maven-for-use-with-github-package-registry#installing-a-package) for installation instructions).
