### ISSUE TITLE
Could not resolve dependencies even with maven repo added.

### ISSUE THREAD

**Issue by Jason5Lee** [breandan/kotlingrad#6]
My `build.gradle.kts` file is like
```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    java
    kotlin("jvm") version "1.3.50"
}

group = "..."
version = "..."

repositories {
    maven("https://maven.pkg.github.com/breandan/kotlingrad")
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("edu.umontreal:kotlingrad:0.1")
    testCompile("junit", "junit", "4.12")
}

configure<JavaPluginConvention> {
    sourceCompatibility = JavaVersion.VERSION_1_8
}
tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}
```
and it fails to resolve `edu.umontreal:kotlingrad:0.1`.

**Comment by breandan** [comment]
Hm, thank you for reporting. Do you have access to the GitHub package registry? I was worried about this, maybe we should use a different registry, like Maven central, until it GHPR becomes public. I’ll update the readme.

https://help.github.com/en/articles/configuring-apache-maven-for-use-with-github-package-registry#installing-a-package

**Comment by breandan** [comment]
Alternatively, you can just download the artifact directly: https://github.com/breandan/kotlingrad/packages/19629

**Comment by breandan** [comment]
I have updated the [installation instructions](https://github.com/breandan/kotlingrad#installation) with the complete Gradle configuration and tested it on a fresh project. Please feel free to reopen if this does not work for some reason.

**Comment by Jason5Lee** [comment]
I follow the new installation instructions. The dependency can be resolved. However, the package seems not to be recognized. I cannot use it in my code. I'm not sure where has gone wrong.

**Comment by breandan** [comment]
Which version are you using?

**Comment by Jason5Lee** [comment]
I have tried 0.1 and 0.2, both are not working.

**Comment by breandan** [comment]
Try using version [`0.2.2`](https://github.com/breandan/kotlingrad/packages/19629) instead, the previous versions were packaged as a fat JAR, which are valid Gradle dependencies according to Gradle, but the IDE is unable to resolve due [a known issue](https://youtrack.jetbrains.com/issue/KT-25709).
